### ISSUE TITLE
Errors on import

### ISSUE THREAD

**Issue by DarrelDonald** [joshuaj1397/BingeWithMe#2]
I got several errors when I tried to import the project.

![image](https://user-images.githubusercontent.com/25857421/32793992-2d4addca-c92d-11e7-8415-18cc36da31bd.png)

**Comment by joshuaj1397** [comment]
This error comes up when you are missing dependencies the project uses. In this case, you're missing API level 25 (Nougat). To download it just click "Install Repository and sync project" then it will ask you to resync your gradle files.

**Comment by DarrelDonald** [comment]
This is what I got after doing that. should i just install what its showing me here too?


![image](https://user-images.githubusercontent.com/25857421/32924421-2b8fa1ec-cb02-11e7-8a06-dd6fe0fde48f.png)

**Comment by joshuaj1397** [comment]
Yes definitely.
